# Generated by Django 4.2.15 on 2025-03-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
            ],
            options={
                "verbose_name": "Kateqoriya",
                "verbose_name_plural": "Kateqoriyalar",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "Kilogram"), ("l", "Litr"), ("pcs", "Ədəd")],
                        max_length=20,
                        verbose_name="Vahid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.category",
                        verbose_name="Kateqoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anbar Məhsulu",
                "verbose_name_plural": "Anbar Məhsulları",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="Əlaqə Məlumatları"),
                ),
            ],
            options={
                "verbose_name": "Təchizatçı",
                "verbose_name_plural": "Təchizatçılar",
            },
        ),
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Miqdar"
                    ),
                ),
                ("purchase_date", models.DateField(verbose_name="Alış Tarixi")),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son İstifadə Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_records",
                        to="inventory.inventoryitem",
                        verbose_name="Anbar Məhsulu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Qeyd",
                "verbose_name_plural": "Stok Qeydləri",
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.supplier",
                verbose_name="Təchizatçı",
            ),
        ),
    ]
