# Generated by Django 4.2.15 on 2025-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrecord",
            name="reason",
            field=models.CharField(
                choices=[
                    ("purchase", "Alış"),
                    ("gift", "Hədiyə"),
                    ("adjustment", "Düzəliş"),
                    ("expired", "Müddəti bitmiş"),
                    ("damaged", "Zədələnmiş"),
                    ("spoilage", "Çürükmüş"),
                    ("theft", "Oğurluq"),
                    ("waste", "İsraf"),
                    ("other", "Digər"),
                ],
                default="purchase",
                max_length=32,
                verbose_name="Səbəb",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="record_type",
            field=models.CharField(
                choices=[("add", "Əlavə"), ("remove", "Çıxış")],
                default="add",
                max_length=16,
                verbose_name="Əməliyyat növü",
            ),
        ),
    ]
