# Generated by Django 4.2.15 on 2025-03-12 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_inventoryrecord_purchase_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrecord",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Məhsulun son istifadə tarixini varsa, burada qeyd edin ki, nə vaxt istifadəyə yararsız olacağını izləyə biləsiniz.",
                null=True,
                verbose_name="Son İstifadə Tarixi",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryrecord",
            name="operation_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="<strong>Əməliyyatın həqiqi baş verdiyi tarixi seçin.</strong><br><br><strong>📌 Alış üçün nümunə:</strong><br>Məhsulu <strong>3 gün əvvəl</strong> almışsınız, lakin <strong>bu gün</strong> sistemə əlavə edirsiniz. Bu halda, məhz <strong>3 gün əvvəlki tarixi</strong> (yəni alışın baş verdiyi günü) seçməlisiniz.<br><br><strong>🚨 Silinmə üçün nümunə:</strong><br>Məhsul <strong>4 gün əvvəl</strong> istifadəyə yararsız olub, lakin siz onu <strong>bu gün</strong> sistemə daxil edirsiniz. Tarixi düzgün göstərmək üçün <strong>4 gün əvvəlki tarixi</strong> qeyd edin.<br><br><em>Əgər bu qaydalara əməl etməsəniz, inventar məlumatları səhv ola bilər və hesabatlar yanlış nəticə verə bilər.</em><hr>",
                verbose_name="Tarix",
            ),
        ),
    ]
