# Generated by Django 4.2.15 on 2025-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_inventoryrecord_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrecord",
            name="record_type",
            field=models.CharField(
                choices=[("add", "Əlavə"), ("remove", "Silinmə")],
                default="add",
                max_length=16,
                verbose_name="Əməliyyat növü",
            ),
        ),
    ]
