# Generated by Django 4.2.15 on 2025-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_inventoryrecord_record_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="price",
            field=models.FloatField(default=0, verbose_name="Qiymət"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("l", "Litr"),
                    ("pcs", "Ədəd"),
                    ("package", "Bağlama"),
                ],
                max_length=20,
                verbose_name="Vahid",
            ),
        ),
    ]
