# Generated by Django 4.2.15 on 2025-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_inventoryrecord_price_alter_inventoryitem_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrecord",
            name="reason",
            field=models.CharField(
                choices=[
                    ("used", "İstifadə edilmiş"),
                    ("sold", "Satılmış"),
                    ("expired", "Müddəti bitmiş"),
                    ("damaged", "Zədələnmiş"),
                    ("spoilage", "Çürükmüş"),
                    ("theft", "Oğurluq"),
                    ("other", "Digər"),
                    ("purchase", "Alış"),
                    ("gift", "Hədiyə"),
                    ("adjustment", "Düzəliş"),
                ],
                default="purchase",
                max_length=32,
                verbose_name="Səbəb",
            ),
        ),
    ]
